name: smile_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  path: ^1.9.0
  flutter_markdown: ^0.7.4+1
  markdown: ^7.0.2
  path_provider: ^2.1.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/inter/Inter-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/inter/Inter-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/inter/Inter-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/inter/Inter-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/inter/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/inter/Inter-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/inter/Inter-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/inter/Inter-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/Inter-Black.otf
          weight: 900
        - asset: assets/fonts/inter/Inter-BlackItalic.otf
          weight: 900
          style: italic
  assets:
    - assets/images/
    - assets/fonts/montserrat/
    - assets/fonts/inter/
    - assets/icons/
    - assets/icons/dark/
    - assets/icons/light/
    - assets/nav_bar/select/
    - assets/nav_bar/unselect/dark/
    - assets/nav_bar/unselect/light/
    - assets/profile_icons/dark/
    - assets/profile_icons/light/
    - assets/splash/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/splash/logo.png
  branding: assets/splash/branding.png
  image_dark: assets/splash/logo.png
  branding_dark: assets/splash/branding_dark.png

  android_12:
    color_dark: "#000000"
    image: assets/splash/android_logo.png
    branding: assets/splash/android_branding.png
    branding_dark: assets/splash/android_branding_dark.png
  android: true
  ios: true
  web: false
